version: '3'

services:

  mysql-local:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shortener
    ports:
      - 3307:3306

  tiniesturlapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: tiniesturlapp
    restart: on-failure
    depends_on:
      - mysql-local
    ports:
      - 8080:8080
      